keys:
  - &host_homelab age1ge4mdmvw4xd6qsfd340whgc9ka3u4d0n90erjasllxacz4x0x9jsgasw06
  - &user_pengeg  age18eysze6z0tzvqra254656ufvkgty82203dwlz0eggkant49cdqtsq4fvak
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_homelab
          - *user_pengeg
